### PR TITLE
add on-screen real-time report, ajax and search engine submission

### PR DESCRIPTION
**Pull request by migliori**
Hi,

**Thanks for your great sitemap generator**.

I needed the crawler to be integrated in an admin panel, and to do all stuff with a single button click
So I added these new features:
- new Ajax demo
- the "generate sitemap" calls the main crawler with Ajax
- the main crawler uses PHP flush to show real-time output (links counter, then textarea with all the crawled urls)
- auto-submission to search engines (can be configured, enabled/disabled in the config file)
- show auto-submission report

I hope all of these can be useful for you & other users

### CODE REVIEW

**Comment by migliori** [comment]
Please could you answer?
If you don't want to merge I have to publish my own package on Composer.
Thanks

**Comment by ivebe** [comment]
@migliori  I'm sorry I haven't seen this before. I would love to merge this in, if you don't mind reopening request.
Only thing is you removed 'ignore_nofollow' logic, I can put it back no big deal. After all it's Hacktoberfest :)

**Comment by migliori** [comment]
Thanks for your answer, a bit late I must say :)
Now I can't reopen the pull request, in between I published my custom version on a new repository: https://github.com/migliori/sitemap-crawler

**Comment by ivebe** [comment]
Do you mind if I merge some parts of it myself?

**Comment by migliori** [comment]
No problem, I did it in the beginning for this purpose, it's just that I don't have access to the original fork anymore.

**Pull request closed without merging**
